# Generated by Django 5.0.3 on 2024-03-23 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('technology_name', models.CharField(max_length=255, verbose_name='Technology Name')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('summary', models.TextField(verbose_name='Summary')),
                ('about_article', models.TextField(verbose_name='About Article')),
                ('article_text', models.TextField(verbose_name='Article Text')),
                ('images', models.ImageField(blank=True, null=True, upload_to='article_images/', verbose_name='Article Images')),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Company Name')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='company_logos/', verbose_name='Company Logo')),
                ('website', models.URLField(blank=True, null=True, verbose_name='Company Website')),
                ('start_date', models.DateField(verbose_name='Start Date')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='End Date')),
                ('role', models.CharField(max_length=255, verbose_name='Role')),
                ('role_summary', models.TextField(verbose_name='Role Summary')),
                ('responsibilities', models.TextField(verbose_name='Responsibilities')),
                ('technologies', models.CharField(max_length=255, verbose_name='Technologies and Programming Languages')),
                ('applications_worked_with', models.CharField(max_length=255, verbose_name='Applications Worked With')),
                ('application_description', models.TextField(verbose_name='Application Description')),
            ],
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Lang Name')),
                ('level', models.CharField(max_length=50, verbose_name='Lang Level')),
            ],
        ),
        migrations.CreateModel(
            name='PortfolioBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('tech_stack', models.CharField(max_length=255, verbose_name='Tech Stack')),
                ('about', models.TextField(verbose_name='About')),
                ('key_responsibilities', models.TextField(verbose_name='Key Responsibilities')),
                ('images', models.ImageField(blank=True, null=True, upload_to='portfolio_images/', verbose_name='Images')),
                ('project_link', models.URLField(blank=True, null=True, verbose_name='Project Link')),
            ],
        ),
        migrations.CreateModel(
            name='ProgrammingLanguage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Programming Lang Name')),
                ('level', models.IntegerField(choices=[(1, 'beginner'), (2, 'elementary'), (3, 'itermediate'), (4, 'advanced'), (5, 'expert')], verbose_name='Programming Lang Level')),
            ],
        ),
        migrations.CreateModel(
            name='Technologies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Technology Name')),
                ('level', models.IntegerField(choices=[(1, 'beginner'), (2, 'elementary'), (3, 'itermediate'), (4, 'advanced'), (5, 'expert')], verbose_name='Technology Level')),
            ],
        ),
    ]
