# Generated by Django 5.0.3 on 2024-03-30 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolioApp', '0003_rename_name_modelwithsvg_icon_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articleblock',
            name='images',
            field=models.ImageField(blank=True, null=True, upload_to='media/article_images/', verbose_name='Article Images'),
        ),
        migrations.AlterField(
            model_name='portfolioblock',
            name='images',
            field=models.ImageField(blank=True, null=True, upload_to='media/portfolio_images/', verbose_name='Images'),
        ),
    ]
